### ISSUE TITLE
Ran out of Resources notice

### ISSUE THREAD

**Issue by brahamw** [mostaphaRoudsari/EmergeSettlement#28]
The "Ran out of Resources"  notice appears during Remapping, even when the bar graphs shows sufficient resources.

**Comment by Butcherluke** [comment]
I've just noticed the same thing.

**Comment by mostaphaRoudsari** [comment]
Thank you both! That is a bug and I have an [open issue](https://github.com/mostaphaRoudsari/SettlementEmerge/issues/22#issuecomment-87988356) for that. Will take a look tonight to see what is wrong there and then will close both.

**Comment by Butcherluke** [comment]
I'm guessing that as this is still open the issue is still going on? I tried it just now (it even works on the train!) but even when I had no demand for forest in my new scenario (just 0.75 Chautauquas - I love that a Chautauqua is now a unit of measurement) I'm still get a map of mostly green pixels.

**Comment by mostaphaRoudsari** [comment]
It is still open. I checked tonight and there is an issue on how I calculate the numbers. They don't match the diagram.Should be an easy fix if I find few hours to work on it this weekend.

![image](https://cloud.githubusercontent.com/assets/2915573/6977338/38ce5bf4-d989-11e4-8a14-67484815d791.png)
